name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11.0-beta - 3.11",
                         "pypy-3.7", "pypy-3.8", "pypy-3.9"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Test using tox
        run: tox -e py
  common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install tox
        run: pip install tox
      - name: Test using tox
        run: tox -e cov,qa
